import argparse
import yaml
import os

NODE_MEMORY_LIMIT = "150m"
COORDINATOR_MEMORY_LIMIT = "256m"

def generate_compose(num_nodes):
    compose = {
        "services": {
            "coordinator": {
                "build": {"context": "./coordinator"},
                "ports": ["8000:8000"],
                "environment": [
                    f"NODE_URLS={','.join([f'http://node{i}:8000' for i in range(1, num_nodes + 1)])}"
                ],
                "volumes": ["./coordinator:/app"],
                "mem_limit": COORDINATOR_MEMORY_LIMIT,
                "memswap_limit": COORDINATOR_MEMORY_LIMIT,
            }
        }
    }

    zones = ["us-east-1a", "us-east-1b", "us-east-1c"]

    for i in range(1, num_nodes + 1):
        zone = zones[(i - 1) % len(zones)]
        compose["services"][f"node{i}"] = {
            "build": {"context": "./node"},
            "ports": [f"{8000 + i}:8000"],
            "environment": [
                f"NODE_ID=node{i}",
                f"NODE_ZONE={zone}"
            ],
            "volumes": ["./node:/app"],
            "mem_limit": NODE_MEMORY_LIMIT,
            "memswap_limit": NODE_MEMORY_LIMIT,
        }

    with open("docker-compose.yml", "w") as f:
        f.write("# Automatically generated by deploy_cluster.py\n")
        yaml.dump(compose, f, sort_keys=False)

    print(f"[+] Successfully generated docker-compose.yml for {num_nodes} nodes.")
    print(f"    Memory caps: coordinator={COORDINATOR_MEMORY_LIMIT}, each node={NODE_MEMORY_LIMIT}")
    print("    Run 'make build' or 'docker compose up --build -d' to start the cluster.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Scale the SecStore cluster.")
    parser.add_argument("--nodes", type=int, default=5, help="Number of storage nodes to deploy")
    args = parser.parse_args()
    
    if args.nodes < 3:
        print("[-] Error: Distributed object store requires at least 3 nodes to be effective.")
        exit(1)
        
    generate_compose(args.nodes)
